webapp/polls/urls.py
from django.conf.urls import url

from . import views

app_name ='polls'

urlpatterns = [
    url(r'^loginid/$', views.loginid, name='login'),
    #url(r'^authen/$',views.authenticate , name = 'authen'),
    # ex: /polls/
    url(r'^signup/$', views.signup, name='signup'),

    url(r'^logoutid/$' , views.logoutid , name = 'logoutid'),

    url(r'^addquestion/$' , views.addquestion , name = 'addquestion'),

    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),

    #url(r'^(?P<question_id>[0-9]+)/logoutid/$', views.logoutid, name='logoutid'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),

    #url(r'^(?P<question_id>[0-9]+)/results/logoutid/$', views.logoutid, name='logoutid'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),

    url(r'^(?P<question_id>[0-9]+)/fetchvote/$', views.fetchvote, name='fetchvote'),

    url(r'^fetchdata/$', views.fetchdata, name='fetch'), 

    url(r'^fetchit/$', views.fetchit, name='fetchit'),

    url(r'^comment/$', views.comment, name='comment'), 

    url(r'^image/$', views.image, name='image'), 

    url(r'^getimage/$', views.getImage, name='getimage'),

    url(r'^fetchQuestion/$', views.fetchQuestion, name='fetchques'),

    url(r'^questionurl/$', views.questionurl, name='quest'),

    url(r'^questionurls/$', views.questionurls, name='quests'),

    url(r'^questionaddreact/$', views.questionaddreact, name='questreact'),

    url(r'^questionadd/$', views.questionadd, name='questadd'),

]

webapp/webapp/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^events/',include('Events.urls'))
]

webapp/polls/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils import timezone
import datetime

# Create your models here.

class Question(models.Model):

    class Meta:
        db_table = "questions"
        
    question_text  =  models.CharField(max_length = 200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
    	#return self.pub_date >= timezone.now() - datetime.timedelta(days = 1)
        return now - datetime.timedelta(days = 1) <= self.pub_date <= now


class Choice(models.Model):

    class Meta:
        db_table = "choices"

    question =  models.ForeignKey(Question,on_delete = models.CASCADE)
    choice_text = models.CharField(max_length = 200)
    votes  = models.IntegerField(default = 0)

    def __str__(self):
        return self.choice_text



class Signup(models.Model):

    class Meta:
        db_table = "userandpass"

    username = models.CharField(max_length = 100)
    password = models.CharField(max_length=50)

    def __str__(sef):
        return self.username


class Comments(models.Model):
    
    class Meta:
        db_table = "Comments"
    
    author = models.CharField(max_length = 100)
    msg = models.CharField(max_length = 500)

    def __str__(self):
        return self.msg

webapp/polls/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from .models import Choice, Question ,Signup ,Comments
from django.utils import timezone

class Login_form(forms.Form):
	username = forms.CharField(label = "your name",max_length = "100")
	password = forms.CharField(max_length=32, widget=forms.PasswordInput)

	def check_login(self):
	     username = self.cleaned_data['username']
	     password = self.cleaned_data['password'] 
	     user = authenticate(username = username,password = password)
	     return user

class Sign_up(forms.Form):
	username = forms.CharField(label = "your name",max_length = "100")
	password = forms.CharField(max_length=32, widget=forms.PasswordInput)

	def create_new_user(self):
		username = self.cleaned_data['username']
		password = self.cleaned_data['password']
		user = User.objects.create_user(username,username,password)
		user.save()


class AddQuestion(forms.Form):
    question = forms.CharField(label = "Add Question" , max_length = "100")
    choice1  = forms.CharField(label = "choice 1" , max_length = "100")
    choice2  = forms.CharField(label = "choice 2" , max_length = "100")
    choice3  = forms.CharField(label = "choice 3", max_length = "100")
    choice4  = forms.CharField(label = "choice 4", max_length = "100" , required = False)
    choice5  = forms.CharField(label = "choice 5", max_length = "100" , required = False)

    def create_new_question(self):
        question = self.cleaned_data['question']
        choice1  = self.cleaned_data['choice1']
        choice2  = self.cleaned_data['choice2']
        choice3  = self.cleaned_data['choice3']
        choice4  = self.cleaned_data['choice4']
        choice5  = self.cleaned_data['choice5']
        q = Question(question_text = question,pub_date = timezone.now())
        q.save()
        cobj1 =  q.choice_set.create(choice_text=choice1, votes=0)
        cobj2 =  q.choice_set.create(choice_text=choice2, votes=0)
        cobj3 =  q.choice_set.create(choice_text=choice3, votes=0)
        choice = [cobj1 , cobj2 , cobj3]
        #q.choice_set.create(choice_text=choice4, votes=0)
        #q.choice_set.create(choice_text=choice5, votes=0)
        return choice



class CommentsForm(forms.Form):
    author = forms.CharField(label = "Name", max_length = "100")
    msg = forms.CharField(label = "Comment" , max_length = "500")

    def create_new_comment(self):
        author = self.cleaned_data['author']
        msg = self.cleaned_data['msg']
        obj = Comments(author = author , msg = msg)
        obj.save()
        return obj


#class Qadd(forms.Form):
#    question = forms.CharField(max_length = "100")
#    name = forms.CharField(max_length = "100")
#    def qadd():
#         q = Question(question_text = question,pub_date = timezone.now())
#         q.save()
#         return q

webapp/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from .models import Choice, Question ,Signup , Comments
from django.template import loader
from django.utils import timezone
from django.contrib import auth
from django.contrib.auth.models import User
from django.http import *
from .forms import Login_form ,Sign_up ,AddQuestion ,CommentsForm 
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
from webapp.tasks import add ,send_simple_message


@login_required(login_url='/polls/loginid/')
def index(request):
    my_questions = []
    latest_question_list = Question.objects.order_by('-pub_date')#[:9]
    for question in latest_question_list:
        if question.pub_date < timezone.now():
            my_questions.append(question)
        
    template = loader.get_template('polls/index.html')
    context = {
        'my_questions': my_questions,
    }
    return HttpResponse(template.render(context, request))

@login_required(login_url='/polls/loginid/')
def detail(request,question_id):
   try:
       question = Question.objects.get(pk=question_id)
   except Question.DoesNotExist:
       raise Http404("Question does not exist")
   return render(request, 'polls/detail.html', {'question': question})

@csrf_exempt
@login_required(login_url='/polls/loginid/')
def vote(request, question_id):
    data = []
    choices = []
    kchoices = []
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        choices = question.choice_set.all()
        for nchoice in choices:
            kchoices.append({"choice" : nchoice.choice_text , "votes" :  nchoice.votes , "choice_id" : nchoice.id})
           
        data  = {"q_text" : question.question_text , "choices" : kchoices}
        return JsonResponse(data = data , safe = False)
        #return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

def fetchvote(request,question_id):
    i = 0
    data = []
    choices = []
    kchoices = []
    question = get_object_or_404(Question, pk=question_id)
    choices = question.choice_set.all()
    for nchoice in choices:
        kchoices.append({"choice" : nchoice.choice_text , "votes" :  nchoice.votes , "choice_id" : nchoice.id ,"inde" : i })
        i = i + 1 
    data  = {"q_text" : question.question_text , "choices" : kchoices }
    print(data)
    return JsonResponse(data = data , safe = False)


@login_required(login_url='/polls/loginid/')
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})


def loginid(request):
    form = Login_form(request.POST or None)
    if request.method == "POST":
        
        if form.is_valid():
            user = form.check_login()
            if user is not None:
                if user.is_active:
                    login(request, user)
                    print ("hello")
                    return HttpResponseRedirect(reverse('polls:index'))
            else :
                print ("bye")
                return HttpResponse("Invalid Email and password")
        else :
            form = Login_form()
    return render(request,'polls/login_user.html', {'form': form })
    
    

#def login(request):
#    if request.method == "POST":
#        form = Login_form(request.POST)
#        if form.is_valid():
 #           print ("hello")

            
#    else:
 #       form = Login_form()

#    return render(request,'polls/login_user.html', {'form': form })


#def authenticate(request):
#    m = User.objects.get(username=request.POST.get('username',False)
#    if m.password == request.POST.get('password' , False):
#        request.session['member_id'] = m.id
#        return HttpResponse("You're logged in.")
#    else:
#        return HttpResponse("Your username and password didn't match.")

#def signup(request):
#     if request.method == "POST":
#        form = Sign_up(request.POST)
#        if form.is_valid():
#            print ("hello")
#            form.create_new_user()
#        else :
#            print ("bye")
#     else:
#        form = Sign_up()
#
#     return render(request,'polls/signup_user.html', {'form': form })
def signup(request):
     if request.method == "POST":
        form = Sign_up(request.POST)
        if form.is_valid():
            print ("hello")
            form.create_new_user()
        else :
            print ("bye")
     else:
        form = Sign_up()

     return render(request,'polls/signup_user.html', {'form': form })


def logoutid(request):
    logout(request)
    return HttpResponseRedirect(reverse('polls:login'))


def addquestion(request):
    if request.method == "POST":
        form = AddQuestion(request.POST)
        if form.is_valid():
            print("hey")
            q = form.create_new_question()
        else:
            print("bye")

    else:
        form = AddQuestion()
    return render(request , 'polls/addquestion.html',{'form':form})


def fetchdata(request):
    data = {"data":[{"id":1388534400000,"text":"Hey there!","author":"Pete Hunt"},{"id":1420070400000,"text":"React is *great*!","author":"Paul O\u2019Shannessy"},{"id":1466768846854,"text":"hello","author":"hey"},{"id":1466768846856,"text":"hello","author":"hello"},{"id":1466768846756,"text":"hello","author":"bye"},{"id":1466768846769,"text":"ello","author":"bye"}]}
    return JsonResponse(data)


def fetchit(request):
    return render(request , 'polls/fetchit.html')



@csrf_exempt
def comment(request):
    if request.method == "POST":
        form = CommentsForm(request.POST)
        if form.is_valid():
            obj = form.create_new_comment()
            jsonDict = {"comment":obj.msg, "author":obj.author}
            return JsonResponse(data = jsonDict,safe = False)
    else:
        form = CommentsForm()
    print (form.errors)
    return render(request , 'polls/comments.html' ,{'form':form})


def image(request):
    print("here")
    data = {"data":[{"url" : "https://s3-us-west-2.amazonaws.com/fs-blog-images/drink_pea2.jpg"},{"url" : "https://s3-us-west-2.amazonaws.com/fs-blog-images/drink_pea1.jpg"}]}
    return JsonResponse(data = data)


def getImage(request):
    num = add.delay(19,9)
    send_simple_message.delay()
    print (num)
    return render(request, 'polls/indexreact.html')


@csrf_exempt
def fetchQuestion(request):
    
    data = []
    kchoice = []
    ques_obj = Question.objects.all()
    for ques_list in ques_obj:
        choice = ques_list.choice_set.all()
        kchoice = []
        
        for nchoices in choice:
            kchoice.append({"choice_id" : nchoices.id , "choice_text" : nchoices.choice_text , "ques_id" : nchoices.question_id , "votes" : nchoices.votes })
            
        data.append({"q_id" : ques_list.id , "question_text" : ques_list.question_text , "choices" :  kchoice})
        

    return JsonResponse(data = data , safe = False)

@csrf_exempt
def questionurl(request):
    return render(request, 'polls/fetchQuestions.html')


@csrf_exempt
def questionaddreact(request):
   
    kchoice = []
    if request.method == "POST":
        form = AddQuestion(request.POST)
        if form.is_valid():
            print("hey")
            choices = form.create_new_question()
            for nchoices in choices:
              kchoice.append({"choice_id" : nchoices.id , "choice_text" : nchoices.choice_text , "ques_id" : nchoices.question_id ,"votes" : nchoices.votes })
              
            jsonDict = {"q_id" : choices[0].question_id , "question_text" : choices[0].question.question_text , "choices" : kchoice}
            return JsonResponse(data = jsonDict , safe =  False)
        else:
            print("bye")

    else:
        form = AddQuestion()
    return render(request , 'polls/addquestion.html',{'form':form})

@csrf_exempt
def questionurls(request):
    return render(request , 'polls/maptofor.html')

@csrf_exempt
def questionadd(request):
    
    name = [] 
    choices = []
    kchoice = []
    if request.method == "POST":
        num = int(request.POST['num'])
        name = request.POST.getlist('name[]')
        question = request.POST['question']
        q = Question(question_text = question,pub_date = timezone.now())
        q.save()
        #print(question)
        #print(name)
        #print(num)
        for i in range(0,num+1):
            choices.append(q.choice_set.create(choice_text=name[i], votes=0))
            #print(name[i])
        #print (request.POST)

        for nchoices in choices:
            kchoice.append({"choice_id" : nchoices.id , "choice_text" : nchoices.choice_text , "ques_id" : nchoices.question_id , "votes" : nchoices.votes })
            
        jsonDict = {"q_id" : choices[0].question_id , "question_text" : choices[0].question.question_text , "choices" : kchoice}
    return JsonResponse(data = jsonDict , safe =  False)
    


        

webapp/polls/templates/polls/addinput.html
var React = require('react');

module.exports = React.createClass({
    addInputField: function(e) {
        e.preventDefault();

        var inputs = this.state.inputs;
        inputs.push({name: null});
        this.setState({inputs : inputs});
    },
    removeInputField: function(index) {
        var inputs = this.state.inputs;
        inputs.splice(index, 1);
        this.setState({inputs : inputs});
    },
    handleSubmit: function (e) {
        e.preventDefault();
        // What do I do here?
    },
    getInitialState: function() {
        return {inputs : []};
    },
    render: function (){
        var inputs = this.state.inputs;
        return (
            // Setting up the form
            // Blah blah
           <div className="form-group">
               <label className="col-sm-3 control-label">Dynamic Inputs</label>
               <div className="col-sm-4">
                   {inputs.map(function (input, index) {
                       var ref = "input_" + index;
                       return (
                           <div className="input-group">
                                <input type="text" className="form-control margin-bottom-12px" placeholder="Enter guid" value={input.name} ref={ref} aria-describedby={ref} />
                                <span className="input-group-addon" onClick={this.removeInputField.bind(this, index)} id={ref} ><i className="fa fa-times"></i></span>
                           </div>
                       )
                   }.bind(this))}
                    <button className="btn btn-success btn-block" onClick={this.addInputField}>Add Input</button>
               </div>
           </div>
        );
    }
});

webapp/polls/templates/polls/addquestion.html
<!-- 
<h1> Add the questions and the choices here </h1>

<form action = "/polls/addquestion/" method = "post">
{% csrf_token %}
Question : <input type = "text" name = "question" placeholder = "Enter the question"><br/>
Choice 1 : <input type = "text" name = "choice1" placeholder = "Enter 1st choice"><br/>
Choice 2 : <input type = "text" name = "choice2" placeholder = "Enter 2nd choice"><br/>
Choice 3 : <input type = "text" name = "choice3" placeholder = "Enter 3rd choice"><br/>
Choice 4 : <input type = "text" name = "choice4" placeholder = "Enter 4th choice"><br/>
Choice 5 : <input type = "text" name = "choice5" placeholder = "Enter 5th choice"><br/>
<input type = "submit" name = "submit" value = "submit">

</form>

-->

<html>
<head>
   <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
   <!--<link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/> -->
   <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
   <!--<script type="text/javascript" src="js/materialize.min.js"></script> -->
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
   <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
</head>

<body>
	<h1> Add Questions and Choices </h1><br />
	<div class = "row">
		<div class = "col s4">
			<form action = "{% url 'polls:addquestion' %}" method = "post">
				{% csrf_token %}
				{{ form.non_field_errors }}
				<div class = "input-field row">
					{{ form.question.errors }}
					<input placeholder="Question" id="question" type="text" class="validate" name = "question">
                    <label for="first_name">Question</label>
                </div>
                <div class = "input-field row">
                	{{ form.Choice1.errors }}
                	<input placeholder = "Choice 1" id ="Choice1" type = "text" class = "validate" name = "choice1">
                	<label for ="Choice1">Choice 1 </label>
                </div>
                <div class = "input-field row">
                	<input placeholder = "Choice 2" id ="Choice2" type = "text" class = "validate" name = "choice2">
                	<label for ="Choice2">Choice 2</label>
                </div>
                <div class = "input-field row">
                	<input placeholder = "Choice 3" id ="Choice3" type = "text" class = "validate" name = "choice3">
                	<label for ="Choice3">Choice 3 </label>
                </div>
                <div class = "input-field row">
                	<input placeholder = "Choice 4" id ="Choice4" type = "text" class = "validate" name = "choice4">
                	<label for ="Choice4">Choice 4 </label>
                </div>
                <div class = "input-field row">
                	<input placeholder = "Choice 5" id ="Choice5" type = "text" class = "validate" name = "choice5">
                	<label for ="Choice5">Choice 5 </label>
                </div>
                <button class="btn waves-effect red col s12" type="submit" name="submit">Submit
                </button>
            </form>
        </div>
    </div>    
</body>
</html>

webapp/polls/templates/polls/cardmapbackup.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>React Tutorial</title>
    <!-- React libs -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.1.0/react.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/react/15.1.0/react-dom.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/babel-core/5.8.34/browser.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/remarkable/1.6.2/remarkable.min.js"></script>
    <!--Materialize libs -->
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--<link type="text/css" rel="stylesheet" href="css/materialize.min.css"  media="screen,projection"/> -->
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <!-- <script type="text/javascript" src="js/materialize.min.js"></script> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
  </head>
  <body>
    <div id="content"></div>
    <script type="text/babel">

    var Questionfetch = React.createClass({
      getInitialState : function(){
        return {data1 : [], question : '' , choices : []  , choice_no : 1};
      },
      componentDidMount: function(){
        $.ajax({
          url : '/polls/fetchQuestion/',
          type  : 'GET',
          dataType : 'json',
          success : function(data){
            this.setState({data1 : data});
          }.bind(this),
          error : function(xhr, status, err){
            alert('inside error');
          }.bind(this)
        });

      },
      handleQuestion : function(e){
        this.setState({question : e.target.value});
      },
      handleChoice : function(e ){
        var id = e.target.id;
        //console.log(id);
        this.state.choices[id] = e.target.value;
        //console.log(this.state.choices[id]);
        this.setState({choices :  this.state.choices})
        //console.log(this.state.choices);
       },
      handleSubmit : function(e){
        e.preventDefault();
        var ques = this.state.data1;
        $.ajax({
          url  : "/polls/questionadd/",
          type : "POST",
          data : {question : this.state.question ,name  : this.state.choices ,num : this.state.choice_no},
          success : function(data){
            alert('hey');
            ques.push({q_id : data.q_id  ,question_text : data.question_text , choices : data.choices});
            this.setState({data1 : ques});
           }.bind(this), 
          error: function(xhr, status, err) {
            alert('this is error');
            console.error(this.props.url, status, err.toString());
          }.bind(this),
      });
      },
      handleInput : function(){
         var choice_no = this.state.choice_no;
         choice_no = choice_no + 1;
         this.setState({choice_no : choice_no});
      },
    render : function(){ 
      var inputchoices = [];
      for(var i = 0 ;i <= this.state.choice_no ; i++)
      {
         inputchoices.push(<div key = {i}><input type = "text" id = {i} onChange = {this.handleChoice} 
           name = "name" value = {this.state.choices[i]} placeholder = {i} /> 
          <br /> 
          </div>);
      }
      return (
        <div>
         <Questionlist data1 = {this.state.data1} />
         <div className = "row">
         <div className = "col s6" >
         <form method = "POST">
          <fieldset>
           <legend> Question Forms </legend>
             <div className="input-field row">
               <label for ="question">Question</label>
               <input type = "text" name ="question" onChange = {this.handleQuestion} 
                  value = {this.state.question} id = "question" className = "validate" /><br />
             </div>
            {inputchoices}
            <button className="btn waves-effect red col s12" type="submit" onClick = {this.handleSubmit}>submit
              </button> <br /><br />
            <button className="btn waves-effect blue col s12" type="button" onClick = {this.handleInput}>Add Input
              </button>            
         </fieldset>
        </form>
        </div>
        </div>

        </div>

        );
    }
    });

    var Questionlist = React.createClass({
      render : function(){
       // var question = this.props.data1.map(function(questions){
       //   return (
       //     <div key = {questions.q_id}>
       //       <Questions ques_id = {questions.q_id} ques_text = {questions.question_text} ques={questions} /><br />
       //     </div>
       //     );
       // });
          var questions;
          var question = [];
          var len = this.props.data1.length;
          for(var i = 0 ; i < len ; i++ )
           {
             questions = this.props.data1[i];
             question.push(
                      <div key = {questions.q_id}>
                         <Questions ques_id = {questions.q_id} ques_text = {questions.question_text} ques={questions} /><br />
                      </div>
                      );
           }
          return (
            <div>
              {question}
            </div>
           );
          }

      }); 

    var Questions = React.createClass({
      getInitialState : function(){
        return {ques_id : '' , choice_id : ''};
      },
      handleRadio : function(e){
        this.setState({choice_id : e.target.value , ques_id : e.target.name});
      },
      handleSubmit : function(e){
         e.preventDefault();
         $.ajax({
           url : '/polls/' + this.state.ques_id +'/vote/',
           type : 'POST',
           data : {choice : this.state.choice_id},
           success : function(data){
             alert('data fetched');
           }.bind(this),
           error : function(e){
            alert('this is error msg');
           }.bind(this)
         });
      },
      render : function(){
        var choices = this.props.ques.choices.map(function(choice){
          return ( 
            <div key = {choice.choice_id}>
                <input type = "radio" value = {choice.choice_id} name = {choice.ques_id}
                  onClick ={this.handleRadio} id={choice.choice_id} />
                <label htmlFor ={choice.choice_id} >{choice.choice_text} </label>    
            </div>
            );
        }.bind(this));
        return (
          <div>
            <div className="row">
              <div className="col s12 m6">
                <div className="card blue-grey darken-1">
                  <div className="card-content white-text">
                    <span className="card-title activator">Question</span><br/>
                      <span> {this.props.ques_id} </span> {this.props.ques_text}
                  </div>
                  <div className="card-reveal">
                    {choices}
                    <br />
                    <button type ="submit" onClick = {this.handleSubmit} className="btn waves-effect blue col s12">
                      submit</button>
                  </div>     
                </div>
              </div>
            </div>
          </div>
          );
      }
    });



    ReactDOM.render(<Questionfetch /> , document.getElementById('content'));

  </script>
</body>
</html>

webapp/polls/templates/polls/detail.html
<!--<h1>{{ question.question_text }}</h1>
<ul>
{% for choicee in question.choice_set.all %}
    <li>{{ choicee.choice_text }}</li>
{% endfor %}
</ul>-->

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
<a href="{% url 'polls:logoutid' %}"> Logout</a>
</form>
    

webapp/polls/templates/polls/index.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
{% if my_questions %}
    <ul>
    {% for questions in my_questions %}
        <!--<li><a href="/polls/{{ questions.id }}/">{{ questions.question_text }}</a></li>-->
        <li><a href="{% url 'polls:detail' questions.id %}">{{ questions.question_text }}</a></li>
    {% endfor %}
    </ul>
    
{% else %}
    <p>No polls are available.</p>
{% endif %}
<a href="{% url 'polls:logoutid' %}"> Logout </a><br />
<a href = "addquestion/"> Add a Question </a>

webapp/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
<a href="{% url 'polls:logoutid' %}"> Logout</a>

webapp/polls/templates/polls/signup_user.html
<h1> This is a Signup form </h1>


<form action = "/polls/signup/" method = "post">
	<table>
	{% csrf_token %}
	{{form.as_table}}
	
	
		<!--
		<tr>
			<td>USERNAME : </td><td><input type = "text" name = "username"></td>
		</tr>
        <tr> 
        	<td>Password : </td><td><input type = "password" name = "password"></td>
        </tr>-->
        
        	<tr><td><input type = "submit" name ="submit" value = "Signup"></td></tr>
    </table>
</form>